name: niki
version: "0.7.11"
grade: stable
base: core18
summary: niki
description: |
    Multimedia Player
    Features:
    Movie player.
    Music player.
    lyric Maker.
    lyric.
    Equalizer.
    Video Balance.
    Music art as background.
    Blur background.
    DLNA Explorer.
    DLNA Controller.
    Camera.
    Disk Drive.
    MPRIS.
    Streaming.
confinement: strict
parts:
  niki:
    after: [granite, inytag, desktop-gnome-platform]
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    source: https://github.com/torikulhabib/niki.git
    override-build: |
        snapcraftctl build
        sed -i -E 's|^(Icon[^=]*)=.*|\1=/usr/share/icons/hicolor/128x128/apps/com.github.torikulhabib.niki.svg|' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/com.github.torikulhabib.niki.desktop
    build-packages:
        - libgirepository1.0-dev
        - valac
        - gobject-introspection
        - gettext
        - libgranite-dev
        - libsoup2.4-dev
        - libgstreamer-plugins-base1.0-dev
        - libclutter-gtk-1.0-dev
        - libclutter-gst-3.0-dev
        - libtag1-dev
        - libtagc0-dev
        - libcanberra-dev
        - libgstreamer-plugins-good1.0-dev
        - libgstreamer-plugins-bad1.0-dev
        - libgupnp-1.0-dev
        - libgupnp-av-1.0-dev
        - libgssdp-1.0-dev
        - libcairo2-dev
    stage-packages:
        - libx11-dev
        - libxau-dev
        - libxcomposite-dev
        - libxcursor-dev
        - libxdamage-dev
        - libxdmcp-dev
        - libxext-dev
        - libxfixes-dev
        - libxi-dev
        - libxinerama-dev
        - libxrandr-dev
        - libxrender-dev
        - libatk1.0-dev
        - libatk-bridge2.0-dev
        - libatspi2.0-dev
        - libcairo2-dev
        - libcairo2
        - libdatrie-dev
        - libepoxy-dev
        - libfontconfig1-dev
        - libfreetype6-dev
        - libgtk-3-dev
        - libgdk-pixbuf2.0-dev
        - libgee-0.8-dev
        - libgraphite2-dev
        - libharfbuzz-dev
        - libpango1.0-dev
        - libpangocairo-1.0-0
        - libpangoft2-1.0-0
        - libpixman-1-dev
        - libpng-dev
        - libthai-dev
        - libwayland-client0
        - libwayland-cursor0
        - libwayland-egl1
        - libwayland-dev
        - libxcb-render0-dev
        - libxcb-shm0-dev
        - libxcb1-dev
        - libxkbcommon-dev
        - libcanberra0
        - libclutter-1.0-0
        - libclutter-gst-3.0-0
        - libclutter-gtk-1.0-0
        - libcogl-pango20
        - libcogl-path20
        - libcogl20
        - libevdev2
        - libgssdp-1.0-3
        - libgstreamer-plugins-base1.0-0
        - libgstreamer1.0-0
        - libgudev-1.0-0
        - libgupnp-1.0-4
        - libgupnp-av-1.0-2
        - libinput10
        - libltdl7
        - libmtdev1
        - libogg0
        - liborc-0.4-0
        - libtag1v5-vanilla
        - libtagc0
        - libtdb1
        - libvorbis0a
        - libvorbisfile3
        - libwacom2
        - gstreamer1.0-libav
        - gstreamer1.0-clutter-3.0
        - gstreamer1.0-plugins-bad
        - gstreamer1.0-plugins-good
        - gstreamer1.0-plugins-base
        - libslang2
        - libglu1-mesa
        - freeglut3
        - libgpm2
        - libx264-152
        - libde265-0
        - youtube-dl
  granite:
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    source: https://github.com/elementary/granite.git
    override-build: |
      snapcraftctl build
    build-packages:
        - libgirepository1.0-dev
        - valac
        - gobject-introspection
        - gettext
    stage-packages:
        - libx11-dev
        - libxau-dev
        - libxcomposite-dev
        - libxcursor-dev
        - libxdamage-dev
        - libxdmcp-dev
        - libxext-dev
        - libxfixes-dev
        - libxi-dev
        - libxinerama-dev
        - libxrandr-dev
        - libxrender-dev
        - libatk1.0-dev
        - libatk-bridge2.0-dev
        - libatspi2.0-dev
        - libcairo2-dev
        - libcairo2
        - libdatrie-dev
        - libepoxy-dev
        - libfontconfig1-dev
        - libfreetype6-dev
        - libgtk-3-dev
        - libgdk-pixbuf2.0-dev
        - libgee-0.8-dev
        - libgraphite2-dev
        - libharfbuzz-dev
        - libpango1.0-dev
        - libpangocairo-1.0-0
        - libpangoft2-1.0-0
        - libpixman-1-dev
        - libpng-dev
        - libthai-dev
        - libwayland-client0
        - libwayland-cursor0
        - libwayland-egl1
        - libwayland-dev
        - libxcb-render0-dev
        - libxcb-shm0-dev
        - libxcb1-dev
        - libxkbcommon-dev
  inytag:
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    source: https://github.com/torikulhabib/InyTag.git
    override-build: |
      snapcraftctl build
    build-packages:
        - libgirepository1.0-dev
        - valac
        - gobject-introspection
        - libtag1-dev
        - libtagc0-dev
        - libtag1v5-vanilla
        - gettext
    stage-packages:
        - libx11-dev
        - libxau-dev
        - libxcomposite-dev
        - libxcursor-dev
        - libxdamage-dev
        - libxdmcp-dev
        - libxext-dev
        - libxfixes-dev
        - libxi-dev
        - libxinerama-dev
        - libxrandr-dev
        - libxrender-dev
        - libatk1.0-dev
        - libatk-bridge2.0-dev
        - libatspi2.0-dev
        - libcairo2-dev
        - libcairo2
        - libdatrie-dev
        - libepoxy-dev
        - libfontconfig1-dev
        - libfreetype6-dev
        - libgtk-3-dev
        - libgdk-pixbuf2.0-dev
        - libgee-0.8-dev
        - libgraphite2-dev
        - libharfbuzz-dev
        - libpango1.0-dev
        - libpangocairo-1.0-0
        - libpangoft2-1.0-0
        - libpixman-1-dev
        - libpng-dev
        - libthai-dev
        - libwayland-client0
        - libwayland-cursor0
        - libwayland-egl1
        - libwayland-dev
        - libxcb-render0-dev
        - libxcb-shm0-dev
        - libxcb1-dev
        - libxkbcommon-dev
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
apps:
  niki:
    command: desktop-launch $SNAP/usr/bin/com.github.torikulhabib.niki
    desktop: usr/share/applications/com.github.torikulhabib.niki.desktop
    plugs:
      - desktop
      - desktop-legacy
      - opengl
      - x11
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
    slots: [ dbus-niki ]
slots:
  dbus-niki:
    interface: dbus
    bus: session
    name: com.github.torikulhabib.niki
plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
